services:
  postgres:
    image: postgres:17-alpine
    container_name: mandaapp_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-mandaapp_prod}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: mandaapp_api
    restart: always
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DATABASE_URL=postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@postgres:5432/${DB_NAME:-mandaapp_prod}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./apps/api/uploads:/app/uploads
      # [Trik DevOps] Mounting host docker socket & root directory untuk mengizinkan 1-Click Update
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/host_app

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: mandaapp_web
    restart: always
    ports:
      - "3080:80"
    depends_on:
      - api

volumes:
  pgdata:
